language: php

php:
  - 8.1
  - 8.2
  - 8.3

dist: noble

services:
  - mysql

env:
  matrix:
    - DB=mysql db_dsn='mysql://root@0.0.0.0/cakephp_test' quoteIdentifiers=false
    - DB=pgsql db_dsn='postgres://postgres@127.0.0.1/cakephp_test' quoteIdentifiers=true
    - DB=pgsql db_dsn='postgres://postgres@127.0.0.1/cakephp_test' quoteIdentifiers=false
    - DB=sqlite db_dsn='sqlite:///:memory:' quoteIdentifiers=false
  global:
    - DEFAULT=1
    - MINIMUMS=0

matrix:
  fast_finish: true

  include:
    - php: 8.1
      env: MINIMUMS=1 DEFAULT=1 DB=mysql db_dsn='mysql://travis@0.0.0.0/cakephp_test'

before_install:
  - if [[ $TRAVIS_PHP_VERSION != "7.4" ]]; then phpenv config-rm xdebug.ini; fi

  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;

  - if [ $DB = 'mysql' ]; then mysql -u root -e 'CREATE DATABASE cakephp_test;'; fi

  - if [ $DB = 'pgsql' ]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi

  - phpenv rehash
  - set +H

before_script:
  - sh -c "if [ '$MINIMUMS' = '0' ]; then composer update --prefer-dist --no-interaction; fi"
  - sh -c "if [ '$MINIMUMS' = '1' ]; then composer update --prefer-dist --no-interaction --prefer-lowest; fi"

script:
  - if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION != 7.* ]]; then vendor/bin/phpunit; fi

  - if [[ $PHPCS = 1 ]]; then vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests; fi

after_success:
  - if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION = 7.* ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
